### PR TITLE
Implementation of agencycountrycode for country specific items

### PR DESCRIPTION
**Pull request by pvanstam**
authcc and delivcc in Keep Alives is now set to NA, which is a valid country code. Suggestion to set it to a dash to prevent the suggestion of a valid CC.

### CODE REVIEW

**Comment by pvanstam** [comment]
- added agencycountrycode element in running-intercept-config.yaml within "agencies".
- default value is empty string (normally it will not occur in the yaml file)
- modified provisioner to read the value and propate as "agencycc"
- send and read via netcomm between provisioner and mediator
- modfied mediator to set the "agencycc" element
- used in keepalives to set specific NL items ('-' as LIID)
-

**Comment by salcock** [comment]
Thank you for submitting this! I'll review it in more detail soon.

One thing I have noticed is the ASN.1 for the LI PS-PDU header (TS 102 232-1) states that the authCountryCode and delivCountryCode must be exactly 2 octets in size. So if we aren't putting a genuine country code in there, we need to put in something that is 2 chars long (i.e. not a single '-' ).

I suspect it would be fine to just use the agency CC as the deliv and auth codes that are set in the keep alive headers, if configured. If not, then put '--' in there I guess.

**Comment by pvanstam** [comment]
> Thank you for submitting this! I'll review it in more detail soon.
> 
> One thing I have noticed is the ASN.1 for the LI PS-PDU header (TS 102 232-1) states that the authCountryCode and delivCountryCode must be exactly 2 octets in size. So if we aren't putting a genuine country code in there, we need to put in something that is 2 chars long (i.e. not a single '-' ).
> 
> I suspect it would be fine to just use the agency CC as the deliv and auth codes that are set in the keep alive headers, if configured. If not, then put '--' in there I guess.

Thanks for your comment and suggestion.
I have modfied the code for Keep Alive accordingly.  So it will be 2 characters, the agencyCC if available and 2 bytes long or else double dash ('--').

**Comment by salcock** [comment]
This has now been merged into the `develop` branch, and will be included in the next OpenLI release.

I've had to do a bit of extra work to integrate this new feature fully -- mainly to ensure that it is supported by our REST API, as well as other means of modifying the running intercept config (such as provisioner SIGHUP, and simply restarting the provisioner after editing the config file).

**Pull request closed without merging**
